name: "build-site"
on:
  push:
    branches:
      - master

jobs:
  build: # run 11ty
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mcfitzgerald/action-build-eleventy # soon to be on marketplace?
      with:
        path: $GITHUB_WORKSPACE
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCE_SA_KEY }}
    - run: |
       gcloud config set project ${{ secrets.GCE_PROJECT }}
       gsutil rsync -r $GITHUB_WORKSPACE/_site ${{ secrets.GS_BUCKET }}