name: Test gcloud commands

on:
  push:
    branches:
    - master

env:
  GCS_BUCKET: gs://mikes_new_bucket
  

jobs:
  print-gcloud-info:
    name: Install and check gcloud utility
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
         with:
          service_account_key: ${{ secrets.GCE_SA_KEY }}
       - run: |
           gcloud config set project ${{ secrets.GCE_PROJECT }}
           gsutil cp ../index.html $GCS_BUCKET/index.html