name: Test gcloud commands

on:
  push:
    branches:
    - master


jobs:
  print-gcloud-info:
    name: Install and check gcloud utility
    runs-on: ubuntu-latest

    steps:
       - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
         with:
          service_account_key: ${{ secrets.GCE_SA_KEY }}
       - run: |
           gcloud config set project ${{ secrets.GCE_PROJECT }}
           gsutil list